# Generated by Django 5.2.13 on 2026-04-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='user',
        ),
        migrations.AddField(
            model_name='scan',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
