# Generated by Django 5.2.13 on 2026-05-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_scan_user_id_scan_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'ordering': ['-created_at']},
        ),
    ]
