# Generated by Django 5.2.13 on 2026-05-02 18:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_scan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
